# Generated by Django 5.1 on 2024-08-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpName', models.CharField(max_length=250)),
                ('EmpDOB', models.CharField(max_length=200)),
                ('EmpEmail', models.EmailField(max_length=254, unique=True)),
                ('EmpMobile', models.IntegerField(default=0)),
                ('EmpGender', models.CharField(max_length=200)),
                ('EmpOccupation', models.CharField(max_length=250)),
                ('EmpIDType', models.CharField(max_length=200)),
                ('EmpIDNumber', models.CharField(max_length=250, unique=True)),
                ('EmpIssueAuthority', models.CharField(max_length=200)),
                ('EmpIssueState', models.CharField(max_length=200)),
                ('EmpIssuedDate', models.CharField(max_length=230)),
                ('EmpExpiryDate', models.CharField(max_length=200)),
            ],
        ),
    ]
